version: 2
jobs:
  quality:
    docker:
      - image: python:3.9

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: quality

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: check quality
          command: |
            tox

  test_py37: &test-template
    docker:
      - image: python:3.7

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: py37

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: run tests
          command: |
            tox

  test_py38:
    <<: *test-template
    docker:
      - image: python:3.8

    environment:
      TOXENV: py38

  test_py39:
    <<: *test-template
    docker:
      - image: python:3.9

    environment:
      TOXENV: py39

  test_py36:
    <<: *test-template
    docker:
      - image: python:3.6

    environment:
      TOXENV: py36

  test_py310:
    <<: *test-template
    docker:
      - image: python:3.10

    environment:
      TOXENV: py310

  test_py311:
    <<: *test-template
    docker:
      - image: python:3.11

    environment:
      TOXENV: py311

  test_py312:
    <<: *test-template
    docker:
      - image: python:3.12

    environment:
      TOXENV: py312

  coverage:
    <<: *test-template

    environment:
      TOXENV: coverage

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: measure coverage
          command: |
            tox
      - run:
          name: upload report
          command: |
            python -m pip install codecov
            codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - test_py37:
          requires:
            - quality
      - test_py38:
          requires:
            - quality
      - test_py39:
          requires:
            - quality
      - test_py36:
          requires:
            - quality
      - test_py310:
          requires:
            - quality
      - test_py311:
          requires:
            - quality
      - test_py312:
          requires:
            - quality
      - coverage:
          requires:
            - quality
